name: Tests

on:
  pull_request

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Setup PHP and Composer
        uses: shivammathur/setup-php@2.31.1
        with:
          php-version: '8.3'
          tools: composer:v2

      - name: Install Dependencies
        run: composer install -q --no-interaction

      - name: Run Test
        env:
          DB_CONNECTION: sqlite
          DB_DATABSAE: ":memory:"
        run: |
          composer prepare
          composer test